### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Norite-dev** [sam-kamerer/sonoff-diy#63]
Hello and thank you for the tool. However, for some reason I can't install it.
running command:
_go install github.com/sam-kamerer/sonoff-diy@master_ 

leads to this error:
_go: github.com/sam-kamerer/sonoff-diy@master: module github.com/sam-kamerer/sonoff-diy@master found (v1.2.3-0.20240103231505-358953555caa), but does not contain package github.com/sam-kamerer/sonoff-diy_

**Comment by sam-kamerer** [comment]
Hi there.
When you use the `go install` command, you need to specify the path to the main package.
For example: `go install github.com/sam-kamerer/sonoff-diy/cmd/sonoff-diy@v1.2.2`
